"""
Django settings for odznaki_gorskie project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ

# Inicjalizacja environ
env = environ.Env(
    # Ustawienie typów i wartości domyślnych
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Wczytaj zmienne środowiskowe z pliku .env
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# SECURITY: Production settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django_extensions',
    'leaflet',
    'tinymce',
    'debug_toolbar',
    'silk',
    'odznaki',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add debug toolbar middleware only in DEBUG mode
if DEBUG:
    MIDDLEWARE.insert(1, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    MIDDLEWARE += ['silk.middleware.SilkyMiddleware']

SILKY_PYTHON_PROFILER = True
SILKY_PYTHON_PROFILER_BINARY = False


ROOT_URLCONF = 'odznaki_gorskie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),      # Główny katalog szablonów (zostawiamy)
            os.path.join(BASE_DIR, 'odznaki', 'templates'), # <-- DODAJ TĘ LINIĘ
        ],
        'APP_DIRS': True, # To ustawienie jest nadal dobre jako fallback
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'odznaki_gorskie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', engine='django.contrib.gis.db.backends.postgis'),
}

# --- Konfiguracja Cache ---
# Używamy prostego cache'u opartego na systemie plików.
# Django utworzy katalog 'django_cache' w podanej lokalizacji.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'django_cache'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pl'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
DEFAULT_CHARSET = 'utf-8'
FILE_CHARSET = 'utf-8'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Ścieżka do katalogu, w którym Django będzie szukać Twoich własnych plików statycznych.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Ścieżka do katalogu, do którego `collectstatic` zbierze wszystkie pliki statyczne na potrzeby produkcji.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Ustawienia dla plików przesyłanych przez użytkownika (Media Files)
# https://docs.djangoproject.com/en/5.2/topics/files/

# Ścieżka URL, pod którą będą dostępne pliki medialne w przeglądarce.
MEDIA_URL = '/media/'

# Absolutna ścieżka w systemie plików, gdzie będą przechowywane przesłane pliki.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Debug Toolbar Configuration (only in DEBUG mode)
if DEBUG:
    INTERNAL_IPS = ['127.0.0.1', 'localhost']
    DEBUG_TOOLBAR_CONFIG = {
        'INTERCEPT_REDIRECTS': False,
        'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG,
    }


# Odczytaj klucz API do Mapy.cz z pliku .env
# Jeśli zmienna nie istnieje w .env, `env()` rzuci błędem, co jest dobre,
# bo od razu wiemy, że czegoś brakuje.
MAPY_CZ_API_KEY = env('MAPY_CZ_API_KEY')

# Globalny przełącznik (na razie go nie potrzebujemy, ale zostawmy na przyszłość)
ENABLE_MAPY_CZ_LAYER = True

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400  # 25 MB (increased for large GPX files)
FILE_UPLOAD_MAX_MEMORY_SIZE = 26214400  # 25 MB


TINYMCE_DEFAULT_CONFIG = {
    'height': 300,
    'width': '100%',
    'menubar': True,
    'plugins': 'advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code fullscreen insertdatetime media table paste code help wordcount',
    'toolbar': 'undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help',
}


# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'odznaki': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# --- ZMIANA POLITYKI BEZPIECZEŃSTWA DLA IFRAME ---
# Zmieniamy domyślną politykę 'DENY' na 'SAMEORIGIN',
# aby pozwolić na osadzanie stron (np. PDF-ów) w ramkach,
# ale tylko w obrębie naszej własnej domeny.
X_FRAME_OPTIONS = 'SAMEORIGIN'
